after_failure:
  - echo $DATABASE_URL
  - cat ./config/database.yml
  - echo $RAILS_ENV
  - bundle exec rake --version
  - ruby env
env:
  - DATABASE_URL=$(curl http://api.postgression.com)
install:
  - bundle install --without development
language: ruby
notifications:
  email:
    recipients:
      - alison.rowland@gsa.gov
      - john.stone@gsa.gov
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
rvm:
  - 2.0.0
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: YyB38JA2cdCYtwpoahGo9PJXHT3ShSP0QkqMQkPQrghz4clBC8Zf8GURiD1R5RoXZpBCVldjfbhMrZWzCmpWBXl7W1PLZaKE1t7ryiYRmzIADMlU2c/yKw0goGwYyI2PpVCgttzK6QajklKoKgzIsFbP+JMCy1/IgMggBg/0eiM=
  app: hyabusa
  on:
    repo: GSA-OCSIT/hyabusa
  run: "rake db:migrate"

